# Generated by Django 2.2.2 on 2019-11-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finals',
            name='chem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finals',
            name='comp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finals',
            name='eng',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finals',
            name='math',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='finals',
            name='phy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term1',
            name='chem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term1',
            name='comp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term1',
            name='eng',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term1',
            name='math',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term1',
            name='phy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term2',
            name='chem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term2',
            name='comp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term2',
            name='eng',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term2',
            name='math',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='term2',
            name='phy',
            field=models.IntegerField(null=True),
        ),
    ]
